spring:
  application:
    name: giay
  datasource:
    url: jdbc:mysql://localhost:3308/giay?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8090
